import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const publicDir = "public";
const rebrandScriptBase = "/brand/13vetura-client.js";
const rebrandScript = `${rebrandScriptBase}?v=20260527-gallery-real-fix`;
const logoUrl = "https://13vetura.com/assets/logo-EwEQIT7A.png";
const business = {
  name: "13vetura",
  phonePrimary: "+38348181116",
  phoneDisplay: "+383 48 181 116",
  phones: "+383 48 181 116 / +383 46 181 117 / +383 45 105 588",
  emailPrimary: "info@13vetura.com",
  emailSales: "sales@13vetura.com",
  addressPrimary: "Rruga Ilaz Kodra nr. 70, Prishtinë (te KEK-u)",
  addressSecondary: "Rruga Përroi i Njelmët 158",
  addressFull: "Rruga Ilaz Kodra nr. 70, Prishtinë (te KEK-u) / Rruga Përroi i Njelmët 158",
  hours: "E Hënë - E Shtunë: 09:00 - 19:00 (UTC+1)"
};

const keyTranslations = new Map([
  ["catalog.auctionDatePresets.next24Hours", "24 orët e ardhshme"],
  ["catalog.auctionDatePresets.next4Days", "4 ditët e ardhshme"],
  ["catalog.auctionDatePresets.fromToday", "Nga sot"],
  ["catalog.auctionDatePresets.fromTomorrow", "Nga nesër"],
  ["catalog.auctionDatePresets.fromNextWeek", "Nga java tjetër"],
  ["catalog.common.copy", "Kopjo"],
  ["catalog.common.favorites", "Të preferuarat"],
  ["catalog.common.loading", "Duke u ngarkuar..."],
  ["catalog.common.no", "Jo"],
  ["catalog.common.notProvided", "Nuk është dhënë"],
  ["catalog.common.only", "Vetëm"],
  ["catalog.common.other", "Tjetër"],
  ["catalog.common.unknown", "E panjohur"],
  ["catalog.common.yes", "Po"],
  ["catalog.favorites.removeAll", "Hiqi të gjitha"],
  ["catalog.favorites.removeEyebrow", "Hiq nga të preferuarat"],
  ["catalog.favorites.removeAllEyebrow", "Pastro të preferuarat"],
  ["catalog.favorites.removeTitle", "Ta hiqni këtë veturë nga të preferuarat?"],
  ["catalog.favorites.removeAllTitle", "T'i hiqni të gjitha veturat e preferuara?"],
  ["catalog.favorites.removeDescription", "Kjo veturë do të hiqet nga lista juaj e ruajtur."],
  ["catalog.favorites.removeAllDescription", "Kjo do të heqë {count} vetura të ruajtura nga të preferuarat."],
  ["catalog.favorites.confirmRemove", "Hiq"],
  ["catalog.favorites.confirmRemoveAll", "Hiqi të gjitha"],
  ["catalog.favorites.cancelRemove", "Anulo"],
  ["catalog.favorites.removedAllNotification", "U hoqën të gjitha të preferuarat"],
  ["catalog.favorites.removedAllDetail", "U hoqën {count} vetura"],
  ["catalog.filterNames.auction", "Ankandi"],
  ["catalog.filterNames.auctionDate", "Data e ankandit"],
  ["catalog.filterNames.excludeExpiredAuctions", "Përjashto ankandet e skaduara"],
  ["catalog.filterNames.bidFrom", "Oferta nga"],
  ["catalog.filterNames.bidTo", "Oferta deri"],
  ["catalog.filterNames.bodyStyle", "Karroceria"],
  ["catalog.filterNames.buyNow", "Bli tani"],
  ["catalog.filterNames.buyNowFrom", "Bli tani nga"],
  ["catalog.filterNames.buyNowTo", "Bli tani deri"],
  ["catalog.filterNames.condition", "Gjendja"],
  ["catalog.filterNames.country", "Shteti"],
  ["catalog.filterNames.cylinders", "Cilindrat"],
  ["catalog.filterNames.damage", "Dëmtimi"],
  ["catalog.filterNames.driveType", "Lloji i tërheqjes"],
  ["catalog.filterNames.engine", "Motori"],
  ["catalog.filterNames.exteriorColor", "Ngjyra e jashtme"],
  ["catalog.filterNames.fuelType", "Karburanti"],
  ["catalog.filterNames.generation", "Gjenerata"],
  ["catalog.filterNames.name", "Emri"],
  ["catalog.filterNames.odometerStatus", "Statusi i kilometrazhit"],
  ["catalog.filterNames.saleStatus", "Statusi i shitjes"],
  ["catalog.filterNames.state", "Shteti/rajoni"],
  ["catalog.filterNames.transmission", "Transmisioni"],
  ["catalog.filterNames.vehicleType", "Lloji i automjetit"],
  ["catalog.filters.title", "Filtrat"],
  ["catalog.filters.clearAll", "Pastro të gjitha"],
  ["catalog.filters.clearSelected", "Pastro zgjedhjen"],
  ["catalog.filters.clearSelectedFor", "Pastro zgjedhjen për {filter}"],
  ["catalog.filters.estimatedPrice", "Çmimi i vlerësuar"],
  ["catalog.filters.clearEstimatedPrice", "Pastro çmimin e vlerësuar"],
  ["catalog.filters.minimumEstimatedPrice", "Çmimi minimal i vlerësuar"],
  ["catalog.filters.maximumEstimatedPrice", "Çmimi maksimal i vlerësuar"],
  ["catalog.filters.make", "Marka"],
  ["catalog.filters.model", "Modeli"],
  ["catalog.filters.search", "Kërko"],
  ["catalog.filters.searchMake", "Kërko markë"],
  ["catalog.filters.searchModel", "Kërko model"],
  ["catalog.filters.loadingMakes", "Duke ngarkuar markat..."],
  ["catalog.filters.manufacturersLoadError", "Markat nuk u ngarkuan"],
  ["catalog.filters.noMakesFound", "Nuk u gjetën marka"],
  ["catalog.filters.noMakesFoundFor", "Nuk u gjetën marka për \"{query}\""],
  ["catalog.filters.clearMake", "Pastro markën"],
  ["catalog.filters.clearModel", "Pastro modelin"],
  ["catalog.filters.selectMakeFirst", "Zgjidh fillimisht markën"],
  ["catalog.filters.selectMakeFirstText", "Zgjidh së paku një markë për të shfaqur modelet."],
  ["catalog.filters.noModelsForSelectedMakes", "Nuk ka modele për markat e zgjedhura"],
  ["catalog.filters.noModelsFound", "Nuk u gjetën modele"],
  ["catalog.filters.allModels", "Të gjitha modelet"],
  ["catalog.filters.addModel", "Shto model"],
  ["catalog.filters.addModelFor", "Shto model për {make}"],
  ["catalog.filters.clearModelSelectionFor", "Pastro zgjedhjen e modelit për {make}"],
  ["catalog.filters.toggleModelsFor", "Shfaq/fshih modelet për {make}"],
  ["catalog.filters.removeMake", "Hiq markën {make}"],
  ["catalog.filters.removeModelFromMake", "Hiq modelin {model} nga {make}"],
  ["catalog.filters.year", "Viti"],
  ["catalog.filters.clearYear", "Pastro vitin"],
  ["catalog.filters.minimumYear", "Viti minimal"],
  ["catalog.filters.maximumYear", "Viti maksimal"],
  ["catalog.filters.odometer", "Kilometrazhi"],
  ["catalog.filters.clearOdometer", "Pastro kilometrazhin"],
  ["catalog.filters.minimumOdometer", "Kilometrazhi minimal"],
  ["catalog.filters.maximumOdometer", "Kilometrazhi maksimal"],
  ["catalog.filters.driveType", "Lloji i tërheqjes"],
  ["catalog.filters.auction", "Ankandi"],
  ["catalog.filters.clearAuction", "Pastro ankandin"],
  ["catalog.filters.auctionDate", "Data e ankandit"],
  ["catalog.filters.auctionDateFrom", "Data e ankandit nga"],
  ["catalog.filters.clearAuctionDate", "Pastro datën e ankandit"],
  ["catalog.filters.datePlaceholder", "Zgjidh datën"],
  ["catalog.filters.damage", "Dëmtimi"],
  ["catalog.filters.clearDamage", "Pastro dëmtimin"],
  ["catalog.filters.selectDamageType", "Kërko ose zgjidh llojin e dëmtimit"],
  ["catalog.filters.noDamageTypesFound", "Nuk u gjetën lloje dëmtimi"],
  ["catalog.filters.showMore", "Shfaq më shumë"],
  ["catalog.filters.showLess", "Shfaq më pak"],
  ["catalog.filters.seeMore", "Shfaq më shumë"],
  ["catalog.filters.all", "Të gjitha"],
  ["catalog.filters.removeOption", "Hiq opsionin {option}"],
  ["catalog.filters.toggleFilterTitle", "Shfaq/fshih filtrin"],
  ["catalog.filters.toggleSpecificFilter", "Shfaq/fshih {filter}"],
  ["catalog.filters.applyFilters", "Apliko ndryshimet"],
  ["catalog.leadModal.eyebrow", "Ndihmë për ankand"],
  ["catalog.leadModal.title", "Kërko konsultim"],
  ["catalog.leadModal.closeAria", "Mbyll dritaren"],
  ["catalog.leadModal.vehicle", "Vetura"],
  ["catalog.leadModal.lotNumber", "Numri i lotit"],
  ["catalog.leadModal.currentBid", "Oferta aktuale"],
  ["catalog.leadModal.buyNow", "Bli tani"],
  ["catalog.leadModal.destination", "Destinacioni"],
  ["catalog.leadModal.destinationPlaceholder", "Shteti / qyteti"],
  ["catalog.leadModal.name", "Emri"],
  ["catalog.leadModal.namePlaceholder", "Emri juaj"],
  ["catalog.leadModal.phone", "Telefoni"],
  ["catalog.leadModal.phonePlaceholder", "Numri i telefonit"],
  ["catalog.leadModal.notes", "Shënime"],
  ["catalog.leadModal.notesPlaceholder", "Detaje shtesë"],
  ["catalog.leadModal.sendRequest", "Dërgo kërkesën"],
  ["catalog.leadModal.callManagers", "Telefono ekipin"],
  ["catalog.leadModal.requestSaved", "Kërkesa u ruajt. Do t'ju kontaktojmë në {phone}."],
  ["catalog.leadModal.interestedInVehicle", "Jeni të interesuar për këtë veturë?"],
  ["catalog.leadModal.helpPurchaseShipping", "Mund t'ju ndihmojmë me blerjen dhe transportin e kësaj veture."],
  ["catalog.leadModal.requestConsultation", "Kërko konsultim"],
  ["catalog.notifications.addedToFavorites", "U shtua te të preferuarat"],
  ["catalog.notifications.removedFromFavorites", "U hoq nga të preferuarat"],
  ["catalog.notifications.vinCopied", "VIN u kopjua"],
  ["catalog.notifications.lotCopied", "Loti u kopjua"],
  ["catalog.notifications.copied", "U kopjua"],
  ["catalog.notifications.copyFailed", "Kopjimi dështoi"],
  ["catalog.options.groups.transmission", "Transmisioni"],
  ["catalog.options.groups.bodyStyle", "Karroceria"],
  ["catalog.options.groups.fuelType", "Karburanti"],
  ["catalog.options.groups.condition", "Gjendja"],
  ["catalog.options.groups.exteriorColor", "Ngjyra e jashtme"],
  ["catalog.options.groups.cylinders", "Cilindrat"],
  ["catalog.options.groups.saleStatus", "Statusi i shitjes"],
  ["catalog.options.transmission.automatic", "Automatik"],
  ["catalog.options.transmission.manual", "Manual"],
  ["catalog.options.driveWheel.frontWheelDrive", "Tërheqje para"],
  ["catalog.options.driveWheel.rearWheelDrive", "Tërheqje pas"],
  ["catalog.options.driveWheel.allWheelDrive", "4x4"],
  ["catalog.options.bodyType.sedan", "Sedan"],
  ["catalog.options.bodyType.wagon", "Karavan"],
  ["catalog.options.bodyType.coupe", "Coupe"],
  ["catalog.options.bodyType.pickup", "Pickup"],
  ["catalog.options.bodyType.suv", "SUV"],
  ["catalog.options.bodyType.cabrio", "Kabrio"],
  ["catalog.options.bodyType.van", "Van"],
  ["catalog.options.bodyType.moto", "Moto"],
  ["catalog.options.bodyType.hatchback", "Hatchback"],
  ["catalog.options.bodyType.roadster", "Roadster"],
  ["catalog.options.bodyType.limousine", "Limuzinë"],
  ["catalog.options.bodyType.truck", "Kamion"],
  ["catalog.options.bodyType.bike", "Motoçikletë"],
  ["catalog.options.bodyType.sportBike", "Moto sportive"],
  ["catalog.options.bodyType.sportCar", "Vetura sportive"],
  ["catalog.options.fuelType.gasoline", "Benzinë"],
  ["catalog.options.fuelType.diesel", "Naftë"],
  ["catalog.options.fuelType.hybrid", "Hibrid"],
  ["catalog.options.fuelType.electric", "Elektrik"],
  ["catalog.options.fuelType.flexible", "Fleksibël"],
  ["catalog.options.fuelType.gas", "Gaz"],
  ["catalog.options.fuelType.hydrogen", "Hidrogjen"],
  ["catalog.options.condition.runAndDrives", "Ndez dhe ecën"],
  ["catalog.options.condition.engineStarts", "Motori ndizet"],
  ["catalog.options.condition.forRepair", "Për riparim"],
  ["catalog.options.condition.toBeDismantled", "Për çmontim"],
  ["catalog.options.condition.notRun", "Nuk ndizet"],
  ["catalog.options.condition.used", "E përdorur"],
  ["catalog.options.condition.unconfirmed", "E pakonfirmuar"],
  ["catalog.options.condition.enhanced", "E përmirësuar"],
  ["catalog.options.color.silver", "Argjendtë"],
  ["catalog.options.color.purple", "Vjollcë"],
  ["catalog.options.color.orange", "Portokalli"],
  ["catalog.options.color.green", "Gjelbër"],
  ["catalog.options.color.red", "Kuqe"],
  ["catalog.options.color.gold", "Ari"],
  ["catalog.options.color.charcoal", "Grafit"],
  ["catalog.options.color.brown", "Kafe"],
  ["catalog.options.color.gray", "Gri"],
  ["catalog.options.color.turquoise", "Turkez"],
  ["catalog.options.color.blue", "Blu"],
  ["catalog.options.color.bronze", "Bronz"],
  ["catalog.options.color.white", "Bardhë"],
  ["catalog.options.color.cream", "Krem"],
  ["catalog.options.color.black", "Zezë"],
  ["catalog.options.color.yellow", "Verdhë"],
  ["catalog.options.color.beige", "Bezhë"],
  ["catalog.options.color.pink", "Rozë"],
  ["catalog.options.color.twoColors", "Dy ngjyra"],
  ["catalog.options.status.notChecked", "Pa kontrolluar"],
  ["catalog.options.status.notOnSale", "Jo në shitje"],
  ["catalog.options.status.sale", "Shitje"],
  ["catalog.options.status.onApproval", "Në miratim"],
  ["catalog.options.status.newAuction", "Ankand i ri"],
  ["catalog.options.status.sold", "Shitur"],
  ["catalog.options.status.failed", "Dështoi"],
  ["catalog.options.status.notSold", "Nuk u shit"],
  ["catalog.options.damage.frontEnd", "Pjesa e përparme"],
  ["catalog.options.damage.rearEnd", "Pjesa e pasme"],
  ["catalog.options.damage.side", "Anësore"],
  ["catalog.options.damage.hail", "Breshër"],
  ["catalog.options.damage.mechanical", "Mekanike"],
  ["catalog.options.damage.minorDentScratches", "Gërvishtje të vogla"],
  ["catalog.options.damage.normalWear", "Konsum normal"],
  ["catalog.options.damage.waterFlood", "Dëmtim nga uji"],
  ["catalog.options.damage.burn", "Djegie"],
  ["catalog.options.damage.theft", "Vjedhje"],
  ["catalog.options.damage.repossession", "Rimarrje"],
  ["catalog.options.odometerStatus.actual", "Aktual"],
  ["catalog.options.odometerStatus.notActual", "Jo aktual"],
  ["catalog.options.odometerStatus.exempt", "I përjashtuar"],
  ["catalog.options.odometerStatus.exceedsMechanicalLimits", "Tejkalon limitet mekanike"],
  ["catalog.options.odometerStatus.hours", "Orë"],
  ["catalog.options.vehicleType.automobile", "Vetura"],
  ["catalog.options.vehicleType.motorcycle", "Motoçikletë"],
  ["catalog.options.vehicleType.trailer", "Rimorkio"],
  ["catalog.options.vehicleType.truck", "Kamion"],
  ["catalog.options.vehicleType.atv", "ATV"],
  ["catalog.options.vehicleType.boat", "Varkë"],
  ["catalog.options.vehicleType.bus", "Autobus"],
  ["catalog.options.vehicleType.industrialEquipment", "Pajisje industriale"],
  ["catalog.page.home", "Ballina"],
  ["catalog.page.searchVehicle", "Kërko"],
  ["catalog.page.allVehicles", "Të gjitha veturat"],
  ["catalog.pagination.previous", "Prapa"],
  ["catalog.pagination.previousPage", "Faqja e mëparshme"],
  ["catalog.pagination.next", "Para"],
  ["catalog.pagination.nextPage", "Faqja tjetër"],
  ["catalog.pagination.page", "Faqja"],
  ["catalog.pagination.pageNumber", "Faqja {page}"],
  ["catalog.quickFilters.all", "Të gjitha"],
  ["catalog.quickFilters.next24Hours", "24 orët e ardhshme"],
  ["catalog.quickFilters.buyNow", "Bli tani"],
  ["catalog.results.auctionStatusFilters", "Filtrat e statusit të ankandit"],
  ["catalog.results.gridView", "Pamje rrjetë"],
  ["catalog.results.rowView", "Pamje listë"],
  ["catalog.results.selectedFilters", "Filtrat e zgjedhur"],
  ["catalog.results.removeFilter", "Hiq {label}"],
  ["catalog.results.loadError", "Katalogu live nuk u ngarkua. Provoni përsëri më vonë."],
  ["catalog.results.noFavoritesYet", "Ende nuk ka vetura të preferuara"],
  ["catalog.results.noVehiclesFound", "Nuk u gjetën vetura"],
  ["catalog.results.noFavoritesHint", "Shtoni vetura te të preferuarat nga katalogu."],
  ["catalog.results.noVehiclesHint", "Provoni të pastroni filtrat ose të kërkoni VIN/lot tjetër."],
  ["catalog.results.backToCatalog", "Kthehu te katalogu"],
  ["catalog.results.openGalleryFor", "Hap galerinë për {title}"],
  ["catalog.results.loadingPhoto", "Duke ngarkuar foton"],
  ["catalog.results.previousPhoto", "Fotoja e mëparshme"],
  ["catalog.results.nextPhoto", "Fotoja tjetër"],
  ["catalog.results.video", "Video"],
  ["catalog.results.spin", "360°"],
  ["catalog.results.openVehicle", "Hap {title}"],
  ["catalog.results.copyVin", "Kopjo VIN {vin}"],
  ["catalog.results.copyLot", "Kopjo lotin {lot}"],
  ["catalog.results.lot", "Loti"],
  ["catalog.results.addToFavorites", "Shto {title} te të preferuarat"],
  ["catalog.results.removeFromFavorites", "Hiq {title} nga të preferuarat"],
  ["catalog.results.engine", "Motori"],
  ["catalog.results.location", "Lokacioni"],
  ["catalog.results.gearbox", "Transmisioni"],
  ["catalog.results.fuel", "Karburanti"],
  ["catalog.results.seller", "Shitësi"],
  ["catalog.results.keyIncluded", "Çelësi i përfshirë"],
  ["catalog.results.documentStatus", "Dokumenti"],
  ["catalog.results.finalAuctionEnded", "Ankandi përfundoi"],
  ["catalog.results.finalBid", "Oferta finale"],
  ["catalog.results.finalPrice", "Çmimi final"],
  ["catalog.results.timedAuction", "Ankand me kohë"],
  ["catalog.results.upcoming", "Në ardhje"],
  ["catalog.results.recentlyFinished", "Sapo përfunduar"],
  ["catalog.results.vin", "VIN"],
  ["catalog.results.auctionStatus", "Statusi i ankandit"],
  ["catalog.results.openDetailsFor", "Hap detajet për {title}"],
  ["catalog.results.details", "Detajet"],
  ["catalog.results.mileage", "Kilometrazhi"],
  ["catalog.results.insurance", "Sigurimi"],
  ["catalog.results.power", "Fuqia"],
  ["catalog.results.engineVolume", "Vëllimi i motorit"],
  ["catalog.results.price", "Çmimi"],
  ["catalog.results.auctionPrice", "Çmimi i ankandit"],
  ["catalog.results.currentBid", "Oferta aktuale"],
  ["catalog.results.lotNumberShort", "Lot №"],
  ["catalog.results.body", "Karroceria"],
  ["catalog.results.color", "Ngjyra"],
  ["catalog.results.keys", "Çelësat"],
  ["catalog.results.drive", "Tërheqja"],
  ["catalog.results.document", "Dokumenti"],
  ["catalog.results.priceInKorea", "Çmimi në Kore: {price}"],
  ["catalog.results.live", "LIVE"],
  ["catalog.results.listedToday", "Listuar sot"],
  ["catalog.results.comingSoon", "Së shpejti"],
  ["catalog.results.tba", "Në pritje"],
  ["catalog.results.status", "Statusi"],
  ["catalog.results.timeLeft", "Koha e mbetur"],
  ["catalog.seo.defaultSourceSummary", "Koreja e Jugut dhe SHBA"],
  ["catalog.seo.usaSourceSummary", "SHBA"],
  ["catalog.seo.southKoreaSourceSummary", "Koreja e Jugut"],
  ["catalog.seo.liveVehicles", "vetura live"],
  ["catalog.seo.vehiclesCount", "{count} vetura"],
  ["catalog.seo.titleBrandModel", "Vetura {brand} {model} nga {sourceSummary}"],
  ["catalog.seo.titleBrand", "Vetura {brand} nga {sourceSummary}"],
  ["catalog.seo.titleSources", "Vetura nga {sourceSummary}"],
  ["catalog.seo.titleDefault", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["catalog.seo.filterSearch", "kërkimi \"{value}\""],
  ["catalog.seo.filterBrand", "marka {value}"],
  ["catalog.seo.filterModel", "modeli {value}"],
  ["catalog.seo.description", "Shfletoni {results}{context} nga {sourceSummary}. Krahasoni VIN, lotin, vitin, çmimin, kilometrazhin dhe gjendjen."],
  ["catalog.seo.keywordCarAuction", "vetura nga SHBA"],
  ["catalog.seo.keywordLiveAuctions", "vetura nga Koreja e Jugut"],
  ["catalog.vehicle.errorLoadDetails", "Detajet e veturës nuk u ngarkuan. Kontrolloni lidhjen me API."],
  ["catalog.vehicle.catalog", "Katalogu"],
  ["catalog.vehicle.close", "Mbyll"],
  ["catalog.vehicle.watchVehicle", "Ruaj"],
  ["catalog.vehicle.watchingVehicle", "E ruajtur"],
  ["catalog.vehicle.salesHistory", "Historiku i shitjeve"],
  ["catalog.vehicle.auctionEndedOn", "Ankandi përfundoi më {date}."],
  ["catalog.vehicle.vehicleSoldOn", "Vetura u shit më {date}."],
  ["catalog.vehicle.onRequest", "Me kërkesë"],
  ["catalog.vehicle.archived", "Arkivuar"],
  ["catalog.vehicle.future", "Në të ardhmen"],
  ["catalog.vehicle.notAvailable", "Nuk është e disponueshme"],
  ["catalog.vehicle.ended", "Përfunduar"],
  ["catalog.vehicle.common", "Të përgjithshme"],
  ["catalog.vehicle.present", "Prezent"],
  ["catalog.vehicle.notPresent", "Jo prezent"],
  ["catalog.vehicle.recordsCount", "{count} regjistrime"],
  ["catalog.vehicle.noSalesHistory", "Kjo veturë nuk ka histori shitjesh."],
  ["catalog.vehicle.date", "Data"],
  ["catalog.vehicle.lotNumberShort", "Lot #"],
  ["catalog.vehicle.similarCars", "Vetura të ngjashme"],
  ["catalog.vehicle.similarAuctions", "Ankande të ngjashme"],
  ["catalog.vehicle.viewAll", "Shiko të gjitha"],
  ["catalog.vehicle.popularModels", "Modele të njohura {brand}"],
  ["catalog.vehicle.photoPending", "Foto në pritje"],
  ["catalog.vehicle.photosPending", "Foto në pritje"],
  ["catalog.vehicle.imagesComingSoon", "Fotot së shpejti"],
  ["catalog.vehicle.photoUnavailable", "Foto e padisponueshme"],
  ["catalog.vehicle.imageCouldNotBeLoaded", "Kjo foto nuk u ngarkua."],
  ["home.seo.title", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["home.seo.description", "Kërkoni vetura nga Koreja e Jugut dhe SHBA me markë, model, vit, mbështetje blerjeje dhe këshilla importi."],
  ["home.hero.title", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["home.hero.subtitle", "Gjetje falas e veturës - paguani vetëm nëse fitojmë"],
  ["home.hero.cta", "Llogarit transportin"],
  ["home.highlights.supercarsEyebrow", "Zgjedhje premium"],
  ["home.highlights.supercarsTitle", "Supervetura"],
  ["home.highlights.motorcycleEyebrow", "Dy rrota"],
  ["home.highlights.motorcycleTitle", "Motoçikleta"],
  ["home.highlights.buyNowEyebrow", "Oferta të gatshme"],
  ["home.highlights.buyNowTitle", "Bli tani"],
  ["home.highlights.seeAll", "Shiko të gjitha"],
  ["home.highlights.empty", "Aktualisht nuk ka vetura të disponueshme."],
  ["home.highlights.noPhoto", "Ende pa foto"],
  ["home.highlights.saleDateEyebrow", "24 orët e ardhshme"],
  ["home.highlights.saleDateTitle", "Mbyllen së shpejti"],
  ["home.highlights.freshEyebrow", "Të reja"],
  ["home.highlights.freshTitle", "Stok i ri"],
  ["home.lead.title", "Gjejmë veturën dhe llogarisim transportin brenda 15 minutave."],
  ["home.lead.subtitle", "Lini kontaktet dhe ne do të gjejmë veturë, do të vlerësojmë transportin dhe do t'u përgjigjemi pyetjeve."],
  ["home.lead.formTitle", "Kërko veturë"],
  ["home.lead.formSubtitle", "Dërgoni kontaktet dhe buxhetin. Ne përgatisim hapat e ardhshëm."],
  ["home.lead.errorTitle", "Plotësoni fushat e theksuara"],
  ["home.lead.labels.name", "Emri"],
  ["home.lead.labels.phone", "Telefoni"],
  ["home.lead.labels.budget", "Buxheti për veturë në ankand"],
  ["home.lead.placeholders.name", "Emri juaj"],
  ["home.lead.placeholders.budget", "Zgjidhni buxhetin"],
  ["home.lead.submit", "Dërgo kërkesën"],
  ["home.lead.terms", "kushtet"],
  ["home.lead.conditions", "rregullat"],
  ["home.lead.modalTitle", "Kërkesa u dërgua"],
  ["home.lead.modalDescription", "Pranuam detajet dhe do t'ju kontaktojmë për hapat e ardhshëm."],
  ["home.lead.modalDone", "Në rregull"],
  ["home.popularMakes.eyebrow", "Shfleto sipas tipit"],
  ["home.popularMakes.title", "Markat e njohura"],
  ["home.search.make", "Marka"],
  ["home.search.searchMake", "Kërko markë..."],
  ["home.search.allMakes", "Të gjitha markat"],
  ["home.search.noMakesFound", "Nuk u gjetën marka."],
  ["home.search.model", "Modeli"],
  ["home.search.searchModel", "Kërko model..."],
  ["home.search.allModels", "Të gjitha modelet"],
  ["home.search.noModelsFound", "Nuk u gjetën modele."],
  ["home.search.generation", "Gjenerata"],
  ["home.search.allGenerations", "Të gjitha gjeneratat"],
  ["home.search.fromYear", "Nga viti"],
  ["home.search.from", "Nga"],
  ["home.search.toYear", "Deri në vitin"],
  ["home.search.to", "Deri"],
  ["home.search.or", "ose"],
  ["home.search.vinPlaceholder", "Kërko me VIN ose numër loti"],
  ["home.search.show", "Kërko"],
  ["home.search.loadingModels", "Duke ngarkuar modelet..."],
  ["home.search.loadingGenerations", "Duke ngarkuar gjeneratat..."],
  ["home.search.vehicleActions.automobile", "Vetura"],
  ["home.search.vehicleActions.motorcycle", "Moto"],
  ["home.search.vehicleActions.atv", "ATV"],
  ["home.search.vehicleActions.trailers", "Rimorkio"],
  ["home.search.vehicleActions.equipment", "Pajisje"],
  ["layout.header.findCar", "Gjej veturë"],
  ["layout.header.search", "Kërko"],
  ["layout.header.logoAlt", "{label} logo"],
  ["layout.header.searchPlaceholder", "Shkruaj markën / modelin / VIN / lotin"],
  ["layout.header.openFavorites", "Hap veturat e preferuara"],
  ["layout.header.favorites", "Të preferuarat"],
  ["layout.header.callAria", `Telefono ${business.name} në {phone}`],
  ["layout.header.call", "Telefon"],
  ["layout.header.openMenu", "Hap menynë"],
  ["layout.header.closeMenu", "Mbyll menynë"],
  ["layout.header.nav.usa", "Vetura nga SHBA"],
  ["layout.header.nav.southKorea", "Vetura nga Koreja e Jugut"],
  ["layout.header.nav.search", "Kërko veturë"],
  ["layout.header.nav.shipping", "Transporti"],
  ["layout.header.nav.howItWorks", "Si funksionon"],
  ["layout.header.nav.blog", "Blog"],
  ["layout.header.nav.contacts", "Kontakt"],
  ["layout.header.quick.featured", "Të veçuara"],
  ["layout.header.quick.buyNow", "Bli tani"],
  ["layout.header.quick.saleStatus", "Statusi i shitjes"],
  ["layout.header.quick.upcoming", "Në ardhje"],
  ["layout.header.quick.sold", "Shitur"],
  ["layout.header.quick.runAndDrive", "Ndez dhe ecën"],
  ["layout.header.quick.engineStarts", "Motori ndizet"],
  ["layout.header.quick.usa", "SHBA"],
  ["layout.header.quick.southKorea", "Koreja e Jugut"],
  ["layout.header.quick.popularMakes", "Markat e njohura"],
  ["layout.header.quick.popularModels", "Modelet e njohura"],
  ["layout.header.quick.bodyStyles", "Karroceria"],
  ["layout.header.quick.fuelTypes", "Karburantet"],
  ["layout.header.quick.priceRanges", "Rangjet e çmimeve"],
  ["layout.footer.description", "Vetura nga Koreja e Jugut dhe SHBA, vlerësime kostoje, këshillim importi dhe mbështetje blerjeje."],
  ["layout.footer.explore", "Eksploro"],
  ["layout.footer.markets", "Tregjet"],
  ["layout.footer.contact", "Kontakt"],
  ["layout.footer.links.search", "Kërko vetura"],
  ["layout.footer.links.shipping", "Transporti"],
  ["layout.footer.links.howItWorks", "Si funksionon"],
  ["layout.footer.links.blog", "Blog"],
  ["layout.footer.links.contacts", "Kontakt"],
  ["layout.footer.links.privacy", "Privatësia"],
  ["layout.footer.links.terms", "Kushtet e përdorimit"],
  ["layout.footer.marketItems.usa", "SHBA"],
  ["layout.footer.marketItems.southKorea", "Koreja e Jugut"],
  ["layout.footer.marketItems.canada", "Kanada"],
  ["layout.footer.marketItems.readyOffers", "Oferta gati për blerje"],
  ["layout.footer.location", "Prishtinë, Kosovë"],
  ["layout.footer.hours", business.hours],
  ["layout.footer.vehicleScope", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["layout.footer.copyright", `© 2026 ${business.name}. Të gjitha të drejtat e rezervuara.`],
  ["pages.favorites.home", "Ballina"],
  ["pages.favorites.breadcrumbCurrent", "Të preferuarat"],
  ["pages.favorites.eyebrow", "Lista e ruajtur"],
  ["pages.favorites.title", "Veturat e preferuara"],
  ["pages.favorites.savedCount", "{count} të ruajtura"],
  ["pages.favorites.emptyTitle", "Ende nuk ka të preferuara"],
  ["pages.favorites.emptyDescription", "Ruani vetura nga katalogu dhe ato do të shfaqen këtu."],
  ["pages.favorites.browseCars", "Shfleto veturat"],
  ["pages.about.seoTitle", `Si funksionon | ${business.name}`],
  ["pages.about.seoDescription", "Shihni procesin nga zgjedhja në ankand deri te transporti, dogana dhe dorëzimi."],
  ["pages.about.badge", "Si funksionon"],
  ["pages.about.title", "Nga ankandi deri te garazhi juaj"],
  ["pages.about.subtitle", "Ne menaxhojmë ofertimin, dokumentet, transportin dhe doganën ndërsa ju zgjidhni veturën."],
  ["pages.about.startSearch", "Fillo kërkimin"],
  ["pages.about.faq", "Pyetje"],
  ["pages.about.processFlow", "Procesi"],
  ["pages.about.sevenSteps", "7 hapa"],
  ["pages.about.liveRoute", "Rruga live"],
  ["pages.about.routeAuction", "Ankandi"],
  ["pages.about.routeCustoms", "Dogana"],
  ["pages.about.routeDelivery", "Dorëzimi"],
  ["pages.about.ctaTitle", "Gati të fillojmë?"],
  ["pages.about.ctaText", "Gjeni veturën e ardhshme në ankand dhe ne e menaxhojmë procesin."],
  ["pages.about.searchInventory", "Kërko stokun"],
  ["pages.about.faqLong", "Pyetje të shpeshta"],
  ["pages.shipping.seoTitle", "Transport veturash nga ankandet e SHBA-së"],
  ["pages.shipping.seoDescription", "Transport veturash nga ankandet amerikane me dokumente dhe mbështetje doganore."],
  ["pages.shipping.imageAlt", "Transport veturash nga SHBA"],
  ["pages.shipping.eyebrow", "Partner logjistike"],
  ["pages.shipping.titleLine1", "Transport"],
  ["pages.shipping.titleLine2", "veturash"],
  ["pages.shipping.titleLine3", "nga SHBA"],
  ["pages.shipping.subtitle", "Partner i besueshëm për transportin e veturave nga ankandet deri në Kosovë."],
  ["pages.shipping.viewAuctions", "Shiko ankandet"],
  ["pages.shipping.contact", "Kontakt"],
  ["pages.shipping.processEyebrow", "Procesi"],
  ["pages.shipping.processTitleLine1", "Si funksionon"],
  ["pages.shipping.processTitleLine2", "transporti"],
  ["pages.shipping.routesEyebrow", "Rrugët"],
  ["pages.shipping.routeTitle", "SHBA → Kosovë"],
  ["pages.shipping.routeDescription", "Transportojmë nga portet kryesore të SHBA-së deri në destinacion."],
  ["pages.shipping.origin", "Origjina"],
  ["pages.shipping.destination", "Destinacioni"],
  ["pages.shipping.destinationValue", "Prishtinë, Kosovë"],
  ["pages.shipping.transit", "Transit"],
  ["pages.shipping.transitValue", "4-10 javë"],
  ["pages.shipping.toKlaipeda", "Deri në Kosovë"],
  ["pages.shipping.usaPorts", "Portet e SHBA-së"],
  ["pages.shipping.klaipedaHub", "Qendra në Kosovë"],
  ["pages.shipping.multipleLoadingPoints", "Pika të shumta ngarkimi"],
  ["pages.shipping.singleDeliveryHub", "Dorëzim i koordinuar"],
  ["pages.shipping.advantagesEyebrow", "Përparësitë"],
  ["pages.shipping.advantagesTitle", "Pse të na zgjidhni?"],
  ["pages.shipping.contactsEyebrow", "Kontakt"],
  ["pages.shipping.contactsTitle", "Keni pyetje?"],
  ["pages.shipping.contactsText", "Ekipi ynë ju ndihmon nga kontakti i parë deri te dorëzimi final."],
  ["pages.privacy.seoTitle", "Politika e privatësisë"],
  ["pages.privacy.seoDescription", `${business.name} shpjegon si përpunohen të dhënat personale nga formularët dhe kërkesat.`],
  ["pages.privacy.title", "Politika e privatësisë"],
  ["pages.privacy.updated", "Përditësuar së fundmi: 21 Maj 2026"],
  ["pages.terms.seoTitle", "Kushtet dhe rregullat"],
  ["pages.terms.seoDescription", `Kushtet që rregullojnë përdorimin e faqes ${business.name}, katalogun dhe kërkesat për konsultim.`],
  ["pages.terms.title", "Kushtet dhe rregullat"],
  ["pages.terms.updated", "Përditësuar së fundmi: 21 Maj 2026"],
  ["pages.notFound.seoTitle", "Faqja nuk u gjet"],
  ["pages.notFound.seoDescription", "Faqja nuk u gjet. Kërkoni vetura ose vazhdoni nga katalogu."],
  ["pages.notFound.eyebrow", "Gabim 404"],
  ["pages.notFound.title", "Faqja nuk u gjet"],
  ["pages.notFound.description", "Faqja mund të jetë zhvendosur ose adresa është shkruar gabim."],
  ["pages.notFound.searchLabel", "Kërko vetura"],
  ["pages.notFound.searchPlaceholder", "Markë, model, VIN ose lot"],
  ["pages.notFound.search", "Kërko"],
  ["pages.notFound.homepage", "Ballina"],
  ["pages.notFound.catalog", "Katalogu"],
  ["pages.notFound.shipping", "Transporti"],
  ["pages.notFound.contacts", "Kontakt"],
  ["pages.blog.home", "Ballina"],
  ["pages.blog.title", "Blog"],
  ["pages.blog.subtitle", "Këshilla praktike për blerje dhe import veturash."],
  ["pages.blog.seoTitle", "Blog për ankande dhe import veturash"],
  ["pages.blog.seoDescription", "Udhëzime praktike për blerje në ankand, kontroll veture dhe vendime importi."],
  ["pages.blog.keyTakeaways", "Pikat kryesore"],
  ["pages.blog.moreFromBlog", "Më shumë nga blogu"],
  ["pages.blog.byAuthor", "Nga {author}"],
  ["pages.blog.articleNotFound", "Artikulli nuk u gjet"]
]);

const exactValueTranslations = new Map([
  ["ImportAuto", business.name],
  ["Vehicles from USA and South Korea", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["Cars from USA and South Korea", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["Cars from the USA and South Korea", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["USA and South Korea", "Koreja e Jugut dhe SHBA"],
  ["Vetura nga SHBA dhe Koreja e Jugut", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["New York, USA", business.addressFull],
  ["Prishtinë, Kosovë", business.addressFull],
  ["Monday - Friday, 10:00 - 18:00", business.hours],
  ["Mon - Fri, 10:00 - 18:00", business.hours],
  ["+1 212 555 0174", business.phoneDisplay],
  ["+1 212 555 0199", business.phoneDisplay],
  ["Contact us", "Na kontaktoni"],
  ["Pick the fastest channel and our team will reply quickly.", "Zgjidhni kanalin më të shpejtë dhe ekipi ynë do t'ju përgjigjet shpejt."],
  ["Need help?", "Keni nevojë për ndihmë?"],
  ["13vetura buyer support", "Mbështetja e blerësve 13vetura"],
  ["Write to us", "Na shkruani"],
  ["Fastest way to contact 13vetura", "Mënyra më e shpejtë për të kontaktuar 13vetura"],
  ["Write 13vetura on Telegram", "Shkruani 13vetura në Telegram"],
  ["13vetura support inbox", "Emaili i mbështetjes 13vetura"],
  ["13vetura office", "Zyra e 13vetura"],
  ["13vetura support hours", "Orari i mbështetjes 13vetura"],
  ["Estimate import costs", "Llogarit kostot e importit"],
  ["Address", "Adresa"],
  ["Working hours", "Orari i punës"],
  ["Working Hours", "Orari i punës"],
  ["ADDRESS", "ADRESA"],
  ["WORKING HOURS", "ORARI I PUNËS"],
  ["POPULAR MAKES", "MARKAT E NJOHURA"]
]);

const phraseTranslations = [
  ["ImportAuto", business.name],
  ["Cars from USA and South Korea", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["cars from USA and South Korea", "vetura nga Koreja e Jugut dhe SHBA"],
  ["Vehicles from USA and South Korea", "Vetura nga Koreja e Jugut dhe SHBA"],
  ["vehicles from USA and South Korea", "vetura nga Koreja e Jugut dhe SHBA"],
  ["USA and South Korea", "Koreja e Jugut dhe SHBA"],
  ["SHBA dhe Koreja e Jugut", "Koreja e Jugut dhe SHBA"],
  ["New York, USA", business.addressFull],
  ["Klaipeda, LT", business.addressFull],
  ["Klaipeda port", business.addressFull],
  ["Prishtinë, Kosovë", business.addressFull],
  ["Monday - Friday, 10:00 - 18:00", business.hours],
  ["Mon - Fri, 10:00 - 18:00", business.hours],
  ["+1 212 555 0174", business.phoneDisplay],
  ["+1 212 555 0199", business.phoneDisplay],
  ["+12125550174", business.phonePrimary],
  ["+12125550199", business.phonePrimary],
  ["tel:+12125550174", `tel:${business.phonePrimary}`],
  ["tel:+12125550199", `tel:${business.phonePrimary}`],
  ["info@importauto.com", business.emailPrimary],
  ["sales@importauto.com", business.emailSales],
  ["shipping.test@importauto.com", business.emailPrimary],
  ["importauto.com", "13vetura.com"],
  ["Contact us", "Na kontaktoni"],
  ["Pick the fastest channel and our team will reply quickly.", "Zgjidhni kanalin më të shpejtë dhe ekipi ynë do t'ju përgjigjet shpejt."],
  ["Need help?", "Keni nevojë për ndihmë?"],
  ["13vetura buyer support", "Mbështetja e blerësve 13vetura"],
  ["Write to us", "Na shkruani"],
  ["Fastest way to contact 13vetura", "Mënyra më e shpejtë për të kontaktuar 13vetura"],
  ["Write 13vetura on Telegram", "Shkruani 13vetura në Telegram"],
  ["13vetura support inbox", "Emaili i mbështetjes 13vetura"],
  ["13vetura office", "Zyra e 13vetura"],
  ["13vetura support hours", "Orari i mbështetjes 13vetura"],
  ["Estimate import costs", "Llogarit kostot e importit"],
  ["Address", "Adresa"],
  ["Working hours", "Orari i punës"],
  ["Working Hours", "Orari i punës"],
  ["ADDRESS", "ADRESA"],
  ["WORKING HOURS", "ORARI I PUNËS"],
  ["POPULAR MAKES", "MARKAT E NJOHURA"],
  ["All rights reserved.", "Të gjitha të drejtat e rezervuara."],
  ["priceCurrency:\"USD\"", "priceCurrency:\"EUR\""],
  ["priceCurrency:\"usd\"", "priceCurrency:\"EUR\""]
].sort((a, b) => b[0].length - a[0].length);

async function listFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const path = join(dir, entry.name);
      return entry.isDirectory() ? listFiles(path) : path;
    })
  );
  return files.flat();
}

function translateValue(value, keyPath = "") {
  if (typeof value === "string") {
    const normalizedKeyPath = keyPath.replace(/^(?:en|ru|ro|uk|pl|bg|ka|lt)\./, "");
    if (keyTranslations.has(normalizedKeyPath)) return keyTranslations.get(normalizedKeyPath);
    const trimmed = value.trim();
    if (exactValueTranslations.has(trimmed)) {
      return value.replace(trimmed, exactValueTranslations.get(trimmed));
    }
    let next = value;
    for (const [from, to] of phraseTranslations) {
      next = next.split(from).join(to);
    }
    return next;
  }

  if (Array.isArray(value)) {
    return value.map((item, index) => translateValue(item, `${keyPath}.${index}`));
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, entryValue]) => [
        key,
        translateValue(entryValue, keyPath ? `${keyPath}.${key}` : key)
      ])
    );
  }

  return value;
}

function patchText(content) {
  let next = content
    .replaceAll("ImportAuto", business.name)
    .replaceAll("/brand/site-logo.svg", logoUrl)
    .replaceAll("+1 212 555 0174", business.phoneDisplay)
    .replaceAll("+1 212 555 0199", business.phoneDisplay)
    .replaceAll("+12125550174", business.phonePrimary)
    .replaceAll("+12125550199", business.phonePrimary)
    .replaceAll("tel:+12125550174", `tel:${business.phonePrimary}`)
    .replaceAll("tel:+12125550199", `tel:${business.phonePrimary}`)
    .replaceAll("https://wa.me/12125550174", `https://wa.me/${business.phonePrimary.replace("+", "")}`)
    .replaceAll("info@importauto.com", business.emailPrimary)
    .replaceAll("sales@importauto.com", business.emailSales)
    .replaceAll("shipping.test@importauto.com", business.emailPrimary)
    .replaceAll("importauto.com", "13vetura.com")
    .replaceAll("New York, USA", "Prishtinë, Kosovë")
    .replaceAll("Monday - Friday, 10:00 - 18:00", business.hours)
    .replaceAll("priceCurrency:\"USD\"", "priceCurrency:\"EUR\"")
    .replaceAll("priceCurrency:\"usd\"", "priceCurrency:\"EUR\"");

  // Rewrite any import-motor photo URLs that slipped into JS/text
  next = next.replaceAll(/https?:\/\/cars2?\.import-motor\.com([^\s"'`<>]+)/gi, (m, p) => {
    const fn = p.split("/").pop();
    return `/images/vehicle/${fn}`;
  });

  next = next
    .replaceAll("`-$${", "`-€${")
    .replaceAll("`$${", "`€${")
    .replaceAll("\"$0\"", "\"€0\"")
    .replaceAll("'$0'", "'€0'");

  return next;
}

function patchHtml(content) {
  let next = patchText(content).replace(/<html([^>]*)lang="[^"]*"/i, "<html$1lang=\"sq\"");
  next = next.replace(/<script\s+defer\s+src="\/brand\/13vetura-client\.js(?:\?[^"]*)?"><\/script>/g, "");
  if (!next.includes(rebrandScript)) {
    next = next.replace("</head>", `<script defer src="${rebrandScript}"></script></head>`);
  }
  next = next.replace(
    /<title>.*?<\/title>/i,
    "<title>13vetura - Vetura nga Koreja e Jugut dhe SHBA</title>"
  );

  // Ensure any remaining import-motor car photos are rewritten to local (for gallery to work)
  next = next.replaceAll(/https?:\/\/cars2?\.import-motor\.com([^\s"'<>]+)/gi, (m, p) => {
    const fn = p.split("/").pop();
    return `/images/vehicle/${fn}`;
  });

  return next;
}

async function patchJsonFile(path) {
  const raw = await readFile(path, "utf8");
  const json = JSON.parse(raw);
  const translated = translateValue(json);
  await writeFile(path, JSON.stringify(translated));
}

async function patchFile(path) {
  if (path.endsWith(".html")) {
    await writeFile(path, patchHtml(await readFile(path, "utf8")));
    return;
  }

  if (path.includes("/_i18n/") && path.endsWith("messages.json")) {
    await patchJsonFile(path);
    return;
  }

  if (/\.(?:js|json|svg|css)$/.test(path)) {
    const current = await readFile(path, "utf8");
    const next = patchText(current);
    if (next !== current) await writeFile(path, next);
  }
}

const files = await listFiles(publicDir);
for (const file of files) {
  if (file.endsWith("13vetura-client.js")) continue;
  await patchFile(file);
}

console.log(`Customized ${files.length} public files for ${business.name}.`);
